
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
# 数据库访问配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicle?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Blct2018mysql
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  rabbitmq:
    addresses: 192.168.28.128:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 200ms
    listener:
      simple:
        acknowledge-mode: manual #手动签收
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
  redis:
    host: 192.168.28.128
    password: blct2018
    database: 1
    jedis:
      pool:
        max-active: 8
        max-wait: 20ms
        max-idle: 500
        min-idle: 0
    timeout: 2000ms
    port: 6379
